#!/usr/bin/env bash
# Offline, explicit provisioning only. Keep input values out of process arguments.
set -euo pipefail
CUBE_DIR="$(cd "$(dirname "$0")/.." && pwd)" python3 - "$@" <<'PY'
import ipaddress
import json
import os
from pathlib import Path
import re
import shutil
import ssl
import stat
import subprocess
import sys
import tempfile
import time


def fail(reason):
    print(f"[bake-creds] {reason}", file=sys.stderr)
    sys.exit(1)


# Never echo unknown arguments: caller may accidentally pass a secret.
args = sys.argv[1:]
if len(args) not in (2, 4) or args[:1] != ['--input']:
    fail('usage: bake-creds.sh --input PRIVATE_JSON [--profile debug]')
if len(args) == 4 and args[2:] != ['--profile', 'debug']:
    fail('only debug profile supported (prod firmware selects plaintext ws://)')

try:
    source = Path(args[1])
    info = source.lstat()
    if not stat.S_ISREG(info.st_mode) or info.st_uid != os.getuid() or info.st_mode & 0o077:
        fail('input must be an owned, private regular file (mode 0600)')

    def unique(pairs):
        result = {}
        for key, value in pairs:
            if key in result:
                raise ValueError('duplicate key')
            result[key] = value
        return result

    data = json.loads(source.read_text(encoding='utf-8'), object_pairs_hook=unique)
    keys = {'WIFI_SSID', 'WIFI_PSK', 'PASETO_TOKEN', 'DEVICE_ID',
            'GATEWAY_HOST', 'GATEWAY_WS_PORT', 'GATEWAY_WS_PATH', 'TRUSTED_CERT_PATH'}
    if not isinstance(data, dict) or set(data) != keys:
        fail('input fields missing or unknown')
    if any(not isinstance(data[k], str) or not data[k] for k in keys - {'GATEWAY_WS_PORT'}):
        fail('input fields must be nonempty strings')
    ssid, psk = data['WIFI_SSID'], data['WIFI_PSK']
    if not 1 <= len(ssid.encode()) <= 32 or '\x00' in ssid:
        fail('invalid WiFi SSID')
    if not (8 <= len(psk.encode()) <= 63 or re.fullmatch(r'[0-9a-fA-F]{64}', psk)) or '\x00' in psk:
        fail('invalid WiFi PSK')
    if not re.fullmatch(r'v4\.local\.[A-Za-z0-9_-]{40,}(?:\.[A-Za-z0-9_-]+)?', data['PASETO_TOKEN']):
        fail('invalid PASETO token format')
    if not re.fullmatch(r'[A-Za-z0-9][A-Za-z0-9._:-]{0,127}', data['DEVICE_ID']):
        fail('invalid device ID')
    host = data['GATEWAY_HOST']
    try:
        ip = ipaddress.ip_address(host)
    except ValueError:
        ip = None
    if ip is not None:
        if not isinstance(ip, ipaddress.IPv4Address) or not any(
            ip in ipaddress.ip_network(net) for net in ('10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16')
        ):
            fail('host must be a LAN IPv4 address or .local hostname')
    elif not re.fullmatch(r'(?=.{1,253}$)(?:[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\.)+local', host, re.I):
        fail('host must be a LAN IPv4 address or .local hostname')
    port = data['GATEWAY_WS_PORT']
    if type(port) is not int or not 1 <= port <= 65535:
        fail('invalid WSS port')
    path = data['GATEWAY_WS_PATH']
    if not re.fullmatch(r'/[A-Za-z0-9/_-]*', path) or path.startswith('//'):
        fail('invalid WebSocket path')

    cert = Path(data['TRUSTED_CERT_PATH'])
    if not cert.is_absolute() or not cert.is_file():
        fail('trusted certificate must be an existing absolute file path')
    # Check certificate validity and SAN coverage offline. This is the supplied
    # outward TLS leaf, not a certificate scraped from a live endpoint.
    def openssl(*flags):
        return subprocess.run(['openssl', 'x509', '-in', str(cert), '-noout', *flags],
                              stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode == 0

    details = ssl._ssl._test_decode_cert(str(cert))
    # OpenSSL checks wildcard DNS SANs; reject its CN fallback when no DNS SAN exists.
    # IP SANs must match literally; -checkip never grants CN-only coverage.
    has_san = any(kind == ('IP Address' if ip else 'DNS') and (not ip or value == host)
                  for kind, value in details.get('subjectAltName', ()))
    if (ssl.cert_time_to_seconds(details['notBefore']) > time.time() or
            not has_san or not openssl('-checkend', '0') or
            not openssl('-checkip' if ip else '-checkhost', host)):
        fail('trusted certificate not currently valid or does not cover host in SAN')
    pem = subprocess.run(['openssl', 'x509', '-in', str(cert), '-outform', 'PEM'],
                         capture_output=True, check=True).stdout

    def c_string(value):
        # Fixed-width octal escapes cannot consume following hex/decimal digits.
        return '"' + ''.join(chr(b) if 32 <= b < 127 and b not in (34, 92)
                             else '\\' + chr(b) if b in (34, 92)
                             else f'\\{b:03o}' for b in value.encode('utf-8')) + '"'

    header = ('// AUTO-GENERATED by scripts/bake-creds.sh. Do NOT edit.\n#pragma once\n\n' +
              ''.join(f'#define SENTIENT_{key:<21} {c_string(data[key])}\n' for key in
                      ('WIFI_SSID', 'WIFI_PSK', 'GATEWAY_HOST', 'GATEWAY_WS_PATH', 'PASETO_TOKEN', 'DEVICE_ID')) +
              f'#define SENTIENT_GATEWAY_WS_PORT  {port}\n#define SENTIENT_DEV_TLS_PIN      1\n')
    out_dir = Path(os.environ['CUBE_DIR']) / 'firmware/main'
    if not out_dir.is_dir():
        fail('firmware/main missing')
    # Stage both private outputs; publish header last so successful provisioning
    # replaces any compile-only placeholder and changes its build dependency.
    staged = []
    backup = None
    try:
        for name, content in (('sentient_dev_gateway.crt', pem),
                              ('sentient_creds.h', header.encode())):
            fd, temp = tempfile.mkstemp(prefix='.bake-', dir=out_dir)
            staged.append((temp, out_dir / name))
            with os.fdopen(fd, 'wb') as stream:
                stream.write(content)
        cert_destination = staged[0][1]
        if cert_destination.exists():
            fd, backup = tempfile.mkstemp(prefix='.bake-', dir=out_dir)
            os.close(fd)
            shutil.copyfile(cert_destination, backup)
        os.replace(*staged[0])
        try:
            os.replace(*staged[1])
        except OSError:
            if backup is not None:
                os.replace(backup, cert_destination)
            else:
                cert_destination.unlink()
            raise
    finally:
        for temp, _ in staged:
            if os.path.exists(temp):
                os.unlink(temp)
        if backup is not None and os.path.exists(backup):
            os.unlink(backup)
except (OSError, ValueError, UnicodeError, subprocess.SubprocessError):
    fail('provisioning failed; check inputs and generated files before building')
PY
