#!/usr/bin/env bash
# bake-creds.sh — reads esp32/cube/.e2e-testing key=value block,
# substitutes into an inlined sentient_creds.h template, writes the baked
# header to firmware/main/sentient_creds.h (gitignored).
set -euo pipefail

PROFILE="debug"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile)
      if [ "$#" -lt 2 ]; then
        echo "[bake-creds] --profile requires a value (debug|prod)" >&2
        exit 1
      fi
      PROFILE="$2"
      shift 2
      ;;
    --profile=*)
      PROFILE="${1#*=}"
      shift
      ;;
    *)
      echo "[bake-creds] unrecognized arg: $1" >&2
      exit 1
      ;;
  esac
done
if [[ "$PROFILE" != "debug" && "$PROFILE" != "prod" ]]; then
  echo "[bake-creds] invalid --profile '$PROFILE' (must be debug|prod)" >&2
  exit 1
fi

CUBE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
E2E="$CUBE_DIR/.e2e-testing"
OUT="$CUBE_DIR/firmware/main/sentient_creds.h"

if [ ! -f "$E2E" ]; then
  echo "ERROR: $E2E missing. Author it first per Task 0.4." >&2
  exit 1
fi

# Extract key=value lines. Tolerant of comment lines + prose around them —
# only lines starting with KEY= (uppercase + underscore) are treated as data.
# Works with bash 3.2 (macOS default) — no associative arrays.
get_val() {
  local key="$1"
  grep -E "^${key}=" "$E2E" | head -1 | cut -d= -f2-
}

REQUIRED="WIFI_SSID WIFI_PSK GATEWAY_HOST GATEWAY_WS_PORT GATEWAY_WS_PATH GATEWAY_LOG_PORT PASETO_TOKEN DEVICE_ID"
for k in $REQUIRED; do
  v="$(get_val "$k")"
  if [ -z "$v" ]; then
    echo "ERROR: $E2E is missing required key: $k" >&2
    exit 1
  fi
done

# Debug profile: mint a fresh PASETO token against the gateway's current
# ~/.sentient/gateway/auth-secret.key + users.json. The PASETO_TOKEN value in
# .e2e-testing is treated as a fallback only — gateway secrets rotate during
# local dev and a stale token rejects with `signature-invalid`. Prod path is
# unchanged.
PASETO_TOKEN_OVERRIDE=""
if [ "$PROFILE" = "debug" ]; then
  REPO_ROOT="$(cd "$CUBE_DIR/../.." && pwd)"
  MINT_SCRIPT="$REPO_ROOT/gateway/scripts/mint-cube-token.ts"
  if [ -f "$MINT_SCRIPT" ]; then
    echo "[bake-creds] debug: minting fresh PASETO token via $MINT_SCRIPT" >&2
    if PASETO_TOKEN_OVERRIDE="$(cd "$REPO_ROOT" && bun run "$MINT_SCRIPT" 2>/dev/null)"; then
      :
    else
      echo "[bake-creds] WARNING: mint failed; falling back to .e2e-testing PASETO_TOKEN" >&2
      PASETO_TOKEN_OVERRIDE=""
    fi
  fi
fi

# Debug profile: override GATEWAY_HOST with the Mac's current LAN IP. The
# .e2e-testing value is treated as a fallback only — the host IP is not
# static on a typical home network. Prod profile keeps the .e2e-testing
# value untouched.
GATEWAY_HOST_OVERRIDE=""
if [ "$PROFILE" = "debug" ]; then
  IFACE="$(route -n get default 2>/dev/null | awk '/interface:/ {print $2}')"
  if [ -n "$IFACE" ]; then
    GATEWAY_HOST_OVERRIDE="$(ipconfig getifaddr "$IFACE" 2>/dev/null || true)"
  fi
  if [ -n "$GATEWAY_HOST_OVERRIDE" ]; then
    echo "[bake-creds] debug: GATEWAY_HOST resolved to ${GATEWAY_HOST_OVERRIDE} via ${IFACE}"
  else
    echo "[bake-creds] WARNING: could not resolve mac ip; falling back to .e2e-testing GATEWAY_HOST=$(get_val GATEWAY_HOST)"
  fi
fi

# Effective value resolver: returns the override for GATEWAY_HOST when set,
# otherwise the .e2e-testing value.
effective_val() {
  local key="$1"
  if [ "$key" = "GATEWAY_HOST" ] && [ -n "$GATEWAY_HOST_OVERRIDE" ]; then
    printf '%s' "$GATEWAY_HOST_OVERRIDE"
  elif [ "$key" = "PASETO_TOKEN" ] && [ -n "$PASETO_TOKEN_OVERRIDE" ]; then
    printf '%s' "$PASETO_TOKEN_OVERRIDE"
  else
    get_val "$key"
  fi
}

# Emit the template (inlined for v2 — no separate .h.in file). Atomic mv at end.
TMP=$(mktemp)
cat >"$TMP" <<'TEMPLATE_EOF'
// AUTO-GENERATED by scripts/bake-creds.sh. Do NOT edit by hand.
// Source values come from esp32/cube/.e2e-testing (gitignored).
#pragma once

#define SENTIENT_WIFI_SSID        "@WIFI_SSID@"
#define SENTIENT_WIFI_PSK         "@WIFI_PSK@"
#define SENTIENT_GATEWAY_HOST     "@GATEWAY_HOST@"
#define SENTIENT_GATEWAY_WS_PORT  @GATEWAY_WS_PORT@
#define SENTIENT_GATEWAY_WS_PATH  "@GATEWAY_WS_PATH@"
#define SENTIENT_GATEWAY_LOG_PORT @GATEWAY_LOG_PORT@
#define SENTIENT_PASETO_TOKEN     "@PASETO_TOKEN@"
#define SENTIENT_DEVICE_ID        "@DEVICE_ID@"
TEMPLATE_EOF

for k in $REQUIRED; do
  v="$(effective_val "$k")"
  # Escape backslash + ampersand + pipe for safe sed s|…|…|g.
  v_esc=$(printf '%s' "$v" | sed -e 's/[\\&|]/\\&/g')
  sed -i.bak "s|@${k}@|${v_esc}|g" "$TMP"
  rm -f "$TMP.bak"
done

mkdir -p "$(dirname "$OUT")"
mv "$TMP" "$OUT"
chmod 0600 "$OUT"
echo "Baked $OUT"
