// Local visual simulation only: no device, camera, microphone, or network access.
const phoneState={setup:'welcome',hub:'hub'};
const phoneTimers={};
const accessDisabled={setup:false,hub:false};
const mini=()=>`<div class="mini-cube">${window.cubeCharacter('ready')}</div>`;
const button=(text,to,style='primary')=>`<button class="pbutton ${style}" data-go="${to}">${text}</button>`;
const row=(title,detail,to,value='›')=>`<${to?'button':'div'} class="row" ${to?`data-go="${to}"`:''}><span><strong>${title}</strong>${detail?`<small>${detail}</small>`:''}</span><span class="${value==='›'?'chevron':'value'}">${value}</span></${to?'button':'div'}>`;
function wifiForm(change=false,error=false){return `<div class="step">${change?'Nearby · Bluetooth connected':'Step 2 of 3 · Wi-Fi'}</div><h2>${change?'Change Wi-Fi':'Connect Wi-Fi'}</h2><p>2.4 GHz networks only.</p>${error?'<div class="info warning" role="alert"><b>Couldn’t join this network.</b><br>Check password, signal, and 2.4 GHz support. Your Cube is still paired.</div>':''}<form data-next="${change?'applying':'joining'}"><label for="${change?'change':'setup'}-network">Network name</label><input id="${change?'change':'setup'}-network" name="network" autocomplete="off" placeholder="Network name" required><label for="${change?'change':'setup'}-password">Wi-Fi password</label><input id="${change?'change':'setup'}-password" type="password" autocomplete="off" placeholder="Enter password" required><label class="check-row"><input type="checkbox" data-show-password>Show password</label><small>Password stays off your Sentient profile.</small><button class="pbutton primary" type="submit">${change?'Update Wi-Fi':'Connect Cube'}</button></form>`}
function hubContent(mode){const offline=mode==='offline',far=mode==='far',disabled=mode==='disabled';return `<div class="hub-hero">${mini()}<h2>Cube</h2><div class="connection"><i class="light" style="${offline||far||disabled?'background:#E9B168':''}"></i>${disabled?'Agent access disabled':offline?'Wi-Fi offline':far?'Not nearby':'Connected'}</div></div><div class="rows">${row('Battery','',null,'82%')}${row('Wi-Fi',offline?'Disconnected':far?'Home · last known':'Home',far?'nearby':'wifi')}${row('Bluetooth','',far?'nearby':null,far?'Connect':'Connected')}${row('Sentient','',null,disabled?'Disabled':offline?'Offline':far?'Last seen yesterday':'Connected')}${row('Device details','','details')}</div><div class="hub-updated"><small>${far?'Last checked yesterday':'Updated just now'}</small><button class="navbtn" data-go="${far?'nearby':mode}" aria-label="Refresh hardware status">${cubeIcon('retry')}</button></div>${far?'<p class="linknote">Move near Cube to update hardware status.</p>':''}<button class="quiet-link" data-go="access">Manage access</button>`}
function content(id){switch(id){
case 'welcome':return `<div class="welcome">${mini()}<h2>Set up Cube</h2><p>Power on Cube and keep it nearby.</p></div>${button('Scan Cube','scan')}<button class="quiet-link" data-go="recover">Already paired?</button>`;
case 'permissions':return `<h2>Set up Cube</h2><div class="rows">${row('Camera','Scan setup code.',null,'')}${row('Bluetooth','Connect nearby.',null,'')}</div>${button('Continue','scan')}`;
case 'scan':return `<div class="step">1 of 3</div><h2>Scan Cube</h2><p>Point your camera at Cube’s screen.</p><div class="camera"><div class="scan-target"><div class="mini-cube"><img src="assets/setup-preview.svg" alt="Preview code"></div></div></div>`;
case 'found':return `<div class="welcome">${mini()}<h2>Cube found</h2></div><p>Connect Cube to your account?</p><div class="info">Anyone using this Cube can speak to your agent.</div>${button('Connect Cube','wifi')}`;
case 'wifi':return wifiForm();
case 'joining':return `<div class="step">3 of 3</div><div class="setup-progress">${mini()}<h2>Connecting…</h2><p>Keep Cube and iPhone nearby.</p></div><ol class="progress-list"><li><span>✓</span> Bluetooth</li><li class="pending"><span>•</span> Wi-Fi and account</li><li><span>○</span> Save phone access</li></ol>`;
case 'done':return `<div class="welcome">${mini()}<h2>Cube connected</h2></div><div class="rows">${row('Tap to wake','First touch doesn’t record.',null,'1')}${row('Hold screen to talk','Release to send.',null,'2')}</div>${button('Done','hub')}`;
case 'denied':return `<div class="empty-glyph">↗</div><h2>Allow nearby setup</h2><p>Bluetooth access is off for Sentient. Allow it in iOS Settings, then return here.</p><div class="info">Cube has not been reset or linked to another account.</div>${button('Open iOS Settings','settings-preview')}${button('Try again','found','')}`;
case 'camera-denied':return `<div class="empty-glyph">↗</div><h2>Allow camera access</h2><p>Sentient needs the camera to scan Cube’s setup code.</p>${button('Open iOS Settings','settings-preview')}${button('Try scanning again','scan','')}`;
case 'settings-preview':return `<h2>Continue in iOS Settings</h2><p>In the app, this opens Sentient’s system permission settings.</p><div class="info">This browser preview does not open or change device settings.</div>${button('Return to setup','permissions')}`;
case 'interrupted':return `<h2>Setup paused</h2><p>Keep Cube nearby to resume.</p>${button('Resume setup','joining')}${button('Not now','welcome','')}`;
case 'failed':return `<h2>Couldn’t connect</h2><p>Check Cube’s power and Wi-Fi.</p>${button('Retry','joining')}${button('Change Wi-Fi','wifi','')}`;
case 'hub':case 'offline':case 'far':case 'disabled':return hubContent(id);
case 'nearby':return `<h2>Cube not nearby</h2><p>Move closer and keep Cube powered on.</p>${button('Connect','hub')}${button('Restore phone access','recover','')}`;
case 'change-wifi':return wifiForm(true);
case 'wifi-error':return wifiForm(true,true);
case 'applying':return `<h2>Checking Wi-Fi…</h2><p>Keep Cube nearby.</p><ol class="progress-list"><li><span>✓</span> Network details sent</li><li class="pending"><span>•</span> Reconnecting and checking status</li></ol>`;
case 'wifi-saved':return `<div class="empty-glyph">${cubeIcon('check')}</div><h2>Wi-Fi updated</h2>${button('Done','hub')}`;
case 'details':return `<h2>Device details</h2><div class="rows">${row('Model','Sentient Cube',null,'')}${row('Firmware','Version reported by device',null,'Preview')}${row('Display','480 × 480 · 2.16-inch AMOLED',null,'')}${row('Connection','2.4 GHz Wi-Fi and Bluetooth',null,'')}</div><p>Use the top + and − buttons to adjust volume on Cube.</p><small>Firmware updates are not part of this initial release.</small>`;
case 'recover':return `<h2>Restore phone access</h2><p>Use your account to manage this Cube on a new phone. Internet required.</p><div class="info warning">Previous phones may retain offline Bluetooth access. This does not re-enable a disabled Cube.</div>${button('Restore access','recovered')}`;
case 'recovered':return `<h2>Phone access restored</h2><p>Move near Cube to connect.</p><small>Agent access is unchanged.</small>${button('Connect nearby','nearby')}`;
case 'access':return `<h2>Manage access</h2><div class="rows">${row('Restore phone access','For a replacement phone. Internet required.','recover')}</div><h3>Disable Cube</h3><div class="access-copy"><p>Stops new agent access. Cube stays linked to your account; history is retained.</p><p>Already-started external work may still finish. A previously authorized phone may still manage Cube locally while offline.</p></div>${button('Disable agent access','confirm-disable','danger')}`;
case 'confirm-disable':return `<h2>Disable this Cube?</h2><p>New conversations and actions will be blocked. This is not a factory reset or an ownership transfer.</p><div class="info warning">Work already started may still finish. Other Cubes sharing today’s conversation will start a fresh conversation on their next authorized input.</div>${button('Disable agent access','disabled','danger')}${button('Keep Cube enabled','hub','')}`;
default:return ''}}
function renderPhone(which,id,focus=false){if(id==='wifi'&&(which==='hub'||['hub','offline','far','disabled'].includes(phoneState[which])))id='change-wifi';if(id==='disabled')accessDisabled[which]=true;if(id==='hub'&&accessDisabled[which])id='disabled';phoneState[which]=id;const root=document.querySelector(`#${which}-phone`);const home=['hub','offline','far','disabled'].includes(id);const start=which==='setup'&&id==='welcome';root.dataset.page=id;root.innerHTML=`<div class="statusbar"><span>9:41</span><i class="island"></i><span aria-label="Phone battery">▰</span></div><nav class="phone-nav" aria-label="${which==='setup'?'Setup':'Hardware'} navigation"><button class="navbtn" data-go="${which==='setup'?'welcome':'hub'}">${start?'‹ Settings':'‹ Back'}</button><strong>${home||start?'':which==='setup'?'Set up Cube':'Cube'}</strong>${which==='setup'&&!home&&!start?'<button class="navbtn" data-go="interrupted">Close</button>':'<span style="width:44px"></span>'}</nav><div class="phone-content">${content(id)}</div><div class="phone-home"></div>`;if(focus){const heading=root.querySelector('h2');heading?.setAttribute('tabindex','-1');heading?.focus({preventScroll:true})}if(which==='setup'){document.querySelector('#setup-demo').innerHTML=id==='scan'?'<button data-demo="found">Simulate scanned code</button><p>Preview scanner only. Real iOS camera permission appears on first use; Bluetooth permission appears before connection.</p>':'<p>Interactive demo · no real account or hardware changes.</p>'}if(id==='joining'||id==='applying'){clearTimeout(phoneTimers[which]);phoneTimers[which]=setTimeout(()=>{if(phoneState[which]===id)renderPhone(which,id==='joining'?'done':'wifi-saved')},2600)}}
document.querySelectorAll('.phone').forEach(root=>{root.addEventListener('click',e=>{const b=e.target.closest('[data-go]');if(b){clearTimeout(phoneTimers[root.dataset.phone]);renderPhone(root.dataset.phone,b.dataset.go,true)}});root.addEventListener('submit',e=>{e.preventDefault();if(!e.target.reportValidity())return;renderPhone(root.dataset.phone,e.target.dataset.next,true)});root.addEventListener('change',e=>{if(e.target.matches('[data-show-password]')){const input=root.querySelector('input[autocomplete="off"][id$="password"]');input.type=e.target.checked?'text':'password'}})});
document.querySelector('#setup-demo').addEventListener('click',e=>{if(e.target.dataset.demo)renderPhone('setup',e.target.dataset.demo,true)});
window.setPhoneScenarios=(setup='welcome',hub='hub')=>{Object.values(phoneTimers).forEach(clearTimeout);accessDisabled.setup=setup==='disabled';accessDisabled.hub=hub==='disabled';renderPhone('setup',setup);renderPhone('hub',hub)};
window.setPhoneScenarios();
