#!/usr/bin/env python3
"""Turn a freshly-compiled requirements lock into the committed vendored lock.

Why this exists instead of `uv pip compile --generate-hashes`: uv sources its
hashes from PyPI's metadata, but a package with no officially-published wheel
for a pinned interpreter (numpy 2.1.3 has no cp314 build) is compiled from
source by `pip wheel`. That artifact is one PyPI never served, so its sha256
can NEVER equal an upstream-sourced hash. Installing the vendored wheels with
a PyPI-sourced lock fails with "THESE PACKAGES DO NOT MATCH THE HASHES" at
offline-install time on the mini -- i.e. at the worst possible moment.

So the committed lock pins the sha256 of the artifact we actually ship. This
script is the only thing that writes those hashes; scripts/build-python-wheels.sh
calls it automatically after every wheel build, which is what keeps the lock and
dist/wheels/<service>/ from drifting apart.

It also enforces a bijection between lock entries and vendored wheels: a lock
entry with no wheel would fail offline install on the mini, and a wheel with no
lock entry is unreviewed code sitting in the release tarball. Both are named,
fail-loud errors here on the build host rather than silent surprises at deploy.

Usage:
  rehash-python-lock.py --lock <lock> --wheels <dir> --service <name> \
                        --requirements <path> --venv <path>
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

# A requirement line as uv emits it: `name==version` optionally continued with
# a trailing backslash. Anything with an environment marker (`;`) is refused
# rather than silently mangled -- see reject_markers().
REQUIREMENT_RE = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s\\;]+)\s*\\?\s*$")
CONTINUATION_PREFIX = "--hash="
# uv annotates provenance as `# via` followed by indented `#   <source>` lines.
VIA_HEADER_RE = re.compile(r"^\s*#\s*via\s*$")
VIA_ENTRY_RE = re.compile(r"^\s*#\s{2,}\S")
# The transient constraints file lives in /tmp and must never be referenced by
# the committed artifact -- a dangling path in a checked-in file is a stale ref.
CONSTRAINT_SOURCE_RE = re.compile(r"^\s*#\s*(via\s+)?-c\s+\S+\s*$")
# Read in 1 MiB blocks: torch is ~106 MB and slurping it whole is pointless.
HASH_BLOCK_BYTES = 1024 * 1024


class LockError(Exception):
    """A named, actionable failure. Raised only for operator-facing causes."""


def normalize(name: str) -> str:
    """PEP 503 name normalization -- `MarkupSafe` and `markup_safe` are one package."""
    return re.sub(r"[-_.]+", "-", name).lower()


def sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(HASH_BLOCK_BYTES), b""):
            digest.update(block)
    return digest.hexdigest()


def index_wheels(wheels_dir: Path) -> dict[tuple[str, str], Path]:
    """Map (normalized name, version) -> wheel path for every vendored wheel."""
    if not wheels_dir.is_dir():
        raise LockError(f"wheels dir {wheels_dir} does not exist — run scripts/build-python-wheels.sh first")
    index: dict[tuple[str, str], Path] = {}
    for wheel in sorted(wheels_dir.glob("*.whl")):
        parts = wheel.name.split("-")
        if len(parts) < 3:
            raise LockError(f"unparseable wheel filename {wheel.name} in {wheels_dir}")
        index[(normalize(parts[0]), parts[1])] = wheel
    if not index:
        raise LockError(f"no wheels in {wheels_dir} — run scripts/build-python-wheels.sh first")
    return index


def reject_markers(line: str) -> None:
    if ";" in line:
        raise LockError(
            f"environment marker in lock line {line.strip()!r} — this script pins one wheel "
            "per requirement and cannot express a conditional dependency"
        )


def build_header(service: str, requirements: str, venv: str, lock: str) -> list[str]:
    """The regenerate recipe, emitted as literally runnable commands.

    A prose placeholder here is how the PyPI-sourced hashes come back on the
    next dependency bump, so every line below is copy-pasteable as-is.
    """
    constraints = f"/tmp/{service}.constraints.txt"
    return [
        "# GENERATED by scripts/rehash-python-lock.py — do not edit by hand.",
        "#",
        f"# Versions are FROZEN FROM THE TESTED VENV at {venv}, not freshly resolved",
        f"# from the ranges in {requirements}. Fresh resolution silently ships whatever",
        "# was latest-matching on the day of the compile; this lock ships what actually ran.",
        "#",
        "# --hash values are the sha256 of the VENDORED wheel under dist/wheels/"
        f"{service}/,",
        "# not PyPI's metadata hash — packages built from source locally (no published",
        "# wheel for the pinned interpreter) produce an artifact PyPI never served.",
        "#",
        "# Regenerate (all four commands, in order):",
        f"#   uv pip freeze --python {venv} --exclude-editable > {constraints}",
        f"#   uv pip compile {requirements} --python {venv} \\",
        f"#       --constraint {constraints} --output-file {lock}",
        "#   ./scripts/build-python-wheels.sh   # rebuilds wheels AND rewrites the hashes below",
        f"#   rm {constraints}",
    ]


def strip_constraint_provenance(lines: list[str]) -> list[str]:
    """Drop `-c <tmp path>` annotations and any `# via` header they left empty."""
    kept = [line for line in lines if not CONSTRAINT_SOURCE_RE.match(line)]
    result: list[str] = []
    for index, line in enumerate(kept):
        is_empty_via = VIA_HEADER_RE.match(line) and (
            index + 1 >= len(kept) or not VIA_ENTRY_RE.match(kept[index + 1])
        )
        if not is_empty_via:
            result.append(line)
    return result


def rewrite_requirements(lines: list[str], wheels: dict[tuple[str, str], Path]) -> tuple[list[str], set[tuple[str, str]]]:
    """Replace every requirement's hash block with the vendored wheel's sha256."""
    out: list[str] = []
    matched: set[tuple[str, str]] = set()
    index = 0
    while index < len(lines):
        line = lines[index]
        match = REQUIREMENT_RE.match(line)
        if not match:
            if not line.lstrip().startswith("#"):
                reject_markers(line)
            out.append(line)
            index += 1
            continue
        name, version = match.group(1), match.group(2)
        index += 1
        while index < len(lines) and lines[index].lstrip().startswith(CONTINUATION_PREFIX):
            index += 1
        key = (normalize(name), version)
        wheel = wheels.get(key)
        if wheel is None:
            raise LockError(
                f"{name}=={version} is in the lock but no matching wheel is vendored — "
                "offline install on the mini would fail; rebuild wheels for this lock"
            )
        matched.add(key)
        out.append(f"{name}=={version} \\")
        out.append(f"    --hash=sha256:{sha256_of(wheel)}")
    return out, matched


def rehash(args: argparse.Namespace) -> None:
    lock_path = Path(args.lock)
    if not lock_path.is_file():
        raise LockError(f"lock file {lock_path} does not exist — compile it first (see the file header)")
    wheels = index_wheels(Path(args.wheels))
    source = lock_path.read_text().splitlines()
    body = [line for line in source if not line.startswith("#")]
    body, matched = rewrite_requirements(body, wheels)
    orphans = sorted(f"{name}=={version}" for name, version in set(wheels) - matched)
    if orphans:
        raise LockError(
            f"vendored wheels with no lock entry: {', '.join(orphans)} — unreviewed packages "
            f"would ship in the release tarball; clear {args.wheels} and rebuild"
        )
    header = build_header(args.service, args.requirements, args.venv, args.lock)
    lines = header + strip_constraint_provenance(body)
    lock_path.write_text("\n".join(line.rstrip() for line in lines).strip() + "\n")
    print(f"✓ {args.service}: rehashed {len(matched)} packages in {lock_path} from {args.wheels}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--lock", required=True, help="lock file to rewrite in place")
    parser.add_argument("--wheels", required=True, help="directory of vendored wheels to hash")
    parser.add_argument("--service", required=True, help="service name, for the header recipe")
    parser.add_argument("--requirements", required=True, help="source requirements.txt, for the header recipe")
    parser.add_argument("--venv", required=True, help="tested venv interpreter, for the header recipe")
    args = parser.parse_args()
    try:
        rehash(args)
    except LockError as error:
        print(f"FAIL: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
