#!/usr/bin/env python3
import os, struct, zlib
from pathlib import Path

ROOT = Path(os.environ.get("FIXTURE_DIR", Path(__file__).parent / "fixtures"))
ROOT.mkdir(parents=True, exist_ok=True)


def png_chunk(kind, data):
    return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data) & 0xffffffff)


def png(path: Path, width=32, height=24):
    rows = []
    for y in range(height):
        row = bytearray([0])
        for x in range(width):
            row += bytes((255 if x < width // 2 else 0, 0 if y < height // 2 else 255, 64))
        rows.append(row)
    path.write_bytes(b"\x89PNG\r\n\x1a\n" + png_chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)) + png_chunk(b"IDAT", zlib.compress(b"".join(rows))) + png_chunk(b"IEND", b""))


def pdf(path: Path, pages, image_jpeg=None):
    objects = []
    def add(data):
        objects.append(data if isinstance(data, bytes) else data.encode())
        return len(objects)
    catalog = add("")
    pages_obj = add("")
    image_obj = None
    if image_jpeg is not None:
        jpg = image_jpeg.read_bytes()
        image_obj = add(f"<< /Type /XObject /Subtype /Image /Width 32 /Height 24 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length {len(jpg)} >>\nstream\n".encode() + jpg + b"\nendstream")
    page_ids = []
    for text, include_image in pages:
        escaped = text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
        ops = f"BT /F1 18 Tf 40 740 Td ({escaped}) Tj ET\n"
        if include_image and image_obj:
            ops += "q 160 0 0 120 40 560 cm /Im0 Do Q\n"
        content = add(f"<< /Length {len(ops.encode())} >>\nstream\n{ops}endstream")
        resources = "<< /Font << /F1 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> >>"
        if include_image and image_obj:
            resources += f" /XObject << /Im0 {image_obj} 0 R >>"
        resources += " >>"
        page_ids.append(add(f"<< /Type /Page /Parent {pages_obj} 0 R /MediaBox [0 0 612 792] /Resources {resources} /Contents {content} 0 R >>"))
    objects[catalog - 1] = f"<< /Type /Catalog /Pages {pages_obj} 0 R >>".encode()
    objects[pages_obj - 1] = f"<< /Type /Pages /Count {len(page_ids)} /Kids [{' '.join(f'{n} 0 R' for n in page_ids)}] >>".encode()
    out = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for i, obj in enumerate(objects, 1):
        offsets.append(len(out)); out += f"{i} 0 obj\n".encode() + obj + b"\nendobj\n"
    xref = len(out)
    out += f"xref\n0 {len(objects)+1}\n0000000000 65535 f \n".encode()
    out += b"".join(f"{off:010d} 00000 n \n".encode() for off in offsets[1:])
    out += f"trailer\n<< /Size {len(objects)+1} /Root {catalog} 0 R >>\nstartxref\n{xref}\n%%EOF\n".encode()
    path.write_bytes(out)


png(ROOT / "known.png")
# JPEG generated by sips before PDFs needing it.
(ROOT / "known.txt").write_text("fixture-alpha\nfixture-beta\n", encoding="utf-8")
(ROOT / "malformed.pdf").write_bytes(b"%PDF-1.7\nnot a pdf\n")
(ROOT / "malformed.png").write_bytes(b"\x89PNG\r\n\x1a\ntruncated")
(ROOT / "oversize-header.png").write_bytes(
    b"\x89PNG\r\n\x1a\n"
    + png_chunk(b"IHDR", struct.pack(">IIBBBBB", 100_000, 100_000, 8, 2, 0, 0, 0))
    + png_chunk(b"IDAT", zlib.compress(b""))
    + png_chunk(b"IEND", b"")
)
pdf(ROOT / "text.pdf", [("KNOWN_TEXT_P1", False), ("KNOWN_TEXT_P2", False)])
pdf(ROOT / "too-many_pages.pdf", [(f"PAGE_{n:03d}", False) for n in range(1, 102)])
if (ROOT / "known.jpg").exists():
    pdf(ROOT / "scanned.pdf", [("", True)], ROOT / "known.jpg")
    pdf(ROOT / "mixed.pdf", [("KNOWN_MIXED_TEXT", True)], ROOT / "known.jpg")
