// Generated from qa/design-refresh/inventory.json for the local QA-only render catalog.
import SwiftUI

struct QAVisualReviewRow { let id: String; let state: String }
let qaVisualReviewRows: [QAVisualReviewRow] = [
    QAVisualReviewRow(id: "ios.setup", state: "idle"),
    QAVisualReviewRow(id: "ios.setup.saving", state: "saving"),
    QAVisualReviewRow(id: "ios.setup.error", state: "error"),
    QAVisualReviewRow(id: "ios.setup.success", state: "success"),
    QAVisualReviewRow(id: "ios.login.picker", state: "loading"),
    QAVisualReviewRow(id: "ios.login.picker.empty", state: "empty"),
    QAVisualReviewRow(id: "ios.login.picker.populated", state: "populated"),
    QAVisualReviewRow(id: "ios.login.picker.error", state: "error"),
    QAVisualReviewRow(id: "ios.login.pin", state: "idle"),
    QAVisualReviewRow(id: "ios.login.pin.submitting", state: "submitting"),
    QAVisualReviewRow(id: "ios.login.pin.error", state: "error"),
    QAVisualReviewRow(id: "ios.splash.thinking", state: "startup thinking minimum duration and readiness wait"),
    QAVisualReviewRow(id: "ios.update.checking", state: "cold update check"),
    QAVisualReviewRow(id: "ios.update.optional", state: "available"),
    QAVisualReviewRow(id: "ios.update.optional.dismissed", state: "dismissed"),
    QAVisualReviewRow(id: "ios.update.optional.installing", state: "installing"),
    QAVisualReviewRow(id: "ios.update.optional.error", state: "error"),
    QAVisualReviewRow(id: "ios.update.mandatory", state: "blocking"),
    QAVisualReviewRow(id: "ios.update.mandatory.installing", state: "installing"),
    QAVisualReviewRow(id: "ios.update.mandatory.error", state: "error"),
    QAVisualReviewRow(id: "ios.shell.chat", state: "authenticated Chat root"),
    QAVisualReviewRow(id: "ios.shell.navigation", state: "native NavigationStack push/pop"),
    QAVisualReviewRow(id: "ios.history.closed", state: "closed"),
    QAVisualReviewRow(id: "ios.history.loading", state: "open loading"),
    QAVisualReviewRow(id: "ios.history.list", state: "open populated and active row"),
    QAVisualReviewRow(id: "ios.history.empty", state: "no sessions"),
    QAVisualReviewRow(id: "ios.history.error", state: "load error and retry"),
    QAVisualReviewRow(id: "ios.history.row-menu", state: "native context menu"),
    QAVisualReviewRow(id: "ios.history.rename", state: "native rename alert"),
    QAVisualReviewRow(id: "ios.history.delete", state: "native destructive alert"),
    QAVisualReviewRow(id: "ios.history.typed-route", state: "dormant typed history route renders EmptyView; drawer owns history"),
    QAVisualReviewRow(id: "ios.chat.empty", state: "new conversation empty state"),
    QAVisualReviewRow(id: "ios.chat.loading", state: "connecting or history loading"),
    QAVisualReviewRow(id: "ios.chat.pending", state: "optimistic queued message"),
    QAVisualReviewRow(id: "ios.chat.user-message", state: "reconciled user message"),
    QAVisualReviewRow(id: "ios.chat.assistant-thinking", state: "assistant thinking before text"),
    QAVisualReviewRow(id: "ios.chat.assistant-responding", state: "streaming assistant response"),
    QAVisualReviewRow(id: "ios.chat.assistant-complete", state: "completed assistant response"),
    QAVisualReviewRow(id: "ios.chat.error", state: "content error"),
    QAVisualReviewRow(id: "ios.chat.error.retry", state: "retry"),
    QAVisualReviewRow(id: "ios.chat.error.reopen-failure", state: "reopen failure"),
    QAVisualReviewRow(id: "ios.chat.cycle-error", state: "error with retry"),
    QAVisualReviewRow(id: "ios.chat.cycle-error.error-without-retry", state: "error without retry"),
    QAVisualReviewRow(id: "ios.chat.cycle-error.dismissed", state: "dismissed"),
    QAVisualReviewRow(id: "ios.chat.connection", state: "connecting"),
    QAVisualReviewRow(id: "ios.chat.connection.lost", state: "lost"),
    QAVisualReviewRow(id: "ios.chat.connection.reconnecting", state: "reconnecting"),
    QAVisualReviewRow(id: "ios.chat.connection.authentication-expired", state: "authentication expired"),
    QAVisualReviewRow(id: "ios.chat.permission", state: "native decision-required permission alert"),
    QAVisualReviewRow(id: "ios.chat.tasks", state: "running"),
    QAVisualReviewRow(id: "ios.chat.tasks.done", state: "done"),
    QAVisualReviewRow(id: "ios.chat.tasks.error", state: "error"),
    QAVisualReviewRow(id: "ios.composer.idle", state: "empty draft and suggestions"),
    QAVisualReviewRow(id: "ios.composer.draft", state: "text draft and enabled send"),
    QAVisualReviewRow(id: "ios.composer.interrupt", state: "active text response interrupt"),
    QAVisualReviewRow(id: "ios.composer.tts", state: "enabled"),
    QAVisualReviewRow(id: "ios.composer.tts.disabled", state: "disabled"),
    QAVisualReviewRow(id: "ios.composer.mic", state: "idle"),
    QAVisualReviewRow(id: "ios.composer.mic.hold", state: "hold"),
    QAVisualReviewRow(id: "ios.composer.mic.locked", state: "Auto semantic listening"),
    QAVisualReviewRow(id: "ios.composer.mic.error", state: "error"),
    QAVisualReviewRow(id: "ios.settings.root", state: "admin"),
    QAVisualReviewRow(id: "ios.settings.root.non-admin", state: "non-admin"),
    QAVisualReviewRow(id: "ios.settings.root.loading", state: "loading"),
    QAVisualReviewRow(id: "ios.settings.memory", state: "idle"),
    QAVisualReviewRow(id: "ios.settings.memory.loading", state: "loading"),
    QAVisualReviewRow(id: "ios.settings.memory.empty", state: "empty"),
    QAVisualReviewRow(id: "ios.settings.memory.dirty", state: "dirty"),
    QAVisualReviewRow(id: "ios.settings.memory.applying", state: "applying"),
    QAVisualReviewRow(id: "ios.settings.memory.success", state: "success"),
    QAVisualReviewRow(id: "ios.settings.memory.error", state: "error"),
    QAVisualReviewRow(id: "ios.settings.calendar-entry", state: "idle"),
    QAVisualReviewRow(id: "ios.settings.calendar-entry.loading", state: "loading"),
    QAVisualReviewRow(id: "ios.settings.calendar-entry.empty", state: "empty"),
    QAVisualReviewRow(id: "ios.settings.calendar-entry.dirty", state: "dirty"),
    QAVisualReviewRow(id: "ios.settings.calendar-entry.applying", state: "applying"),
    QAVisualReviewRow(id: "ios.settings.calendar-entry.success", state: "success"),
    QAVisualReviewRow(id: "ios.settings.calendar-entry.error", state: "error"),
    QAVisualReviewRow(id: "ios.settings.personalities", state: "idle"),
    QAVisualReviewRow(id: "ios.settings.personalities.loading", state: "loading"),
    QAVisualReviewRow(id: "ios.settings.personalities.empty", state: "empty"),
    QAVisualReviewRow(id: "ios.settings.personalities.dirty", state: "dirty"),
    QAVisualReviewRow(id: "ios.settings.personalities.applying", state: "applying"),
    QAVisualReviewRow(id: "ios.settings.personalities.success", state: "success"),
    QAVisualReviewRow(id: "ios.settings.personalities.error", state: "error"),
    QAVisualReviewRow(id: "ios.settings.voice", state: "idle"),
    QAVisualReviewRow(id: "ios.settings.voice.loading", state: "loading"),
    QAVisualReviewRow(id: "ios.settings.voice.empty", state: "empty"),
    QAVisualReviewRow(id: "ios.settings.voice.dirty", state: "dirty"),
    QAVisualReviewRow(id: "ios.settings.voice.applying", state: "applying"),
    QAVisualReviewRow(id: "ios.settings.voice.success", state: "success"),
    QAVisualReviewRow(id: "ios.settings.voice.error", state: "error"),
    QAVisualReviewRow(id: "ios.settings.voice-add", state: "idle"),
    QAVisualReviewRow(id: "ios.settings.voice-add.loading", state: "loading"),
    QAVisualReviewRow(id: "ios.settings.voice-add.empty", state: "empty"),
    QAVisualReviewRow(id: "ios.settings.voice-add.dirty", state: "dirty"),
    QAVisualReviewRow(id: "ios.settings.voice-add.applying", state: "applying"),
    QAVisualReviewRow(id: "ios.settings.voice-add.success", state: "success"),
    QAVisualReviewRow(id: "ios.settings.voice-add.error", state: "error"),
    QAVisualReviewRow(id: "ios.settings.voice-fish", state: "idle"),
    QAVisualReviewRow(id: "ios.settings.voice-fish.loading", state: "loading"),
    QAVisualReviewRow(id: "ios.settings.voice-fish.empty", state: "empty"),
    QAVisualReviewRow(id: "ios.settings.voice-fish.dirty", state: "dirty"),
    QAVisualReviewRow(id: "ios.settings.voice-fish.applying", state: "applying"),
    QAVisualReviewRow(id: "ios.settings.voice-fish.success", state: "success"),
    QAVisualReviewRow(id: "ios.settings.voice-fish.error", state: "error"),
    QAVisualReviewRow(id: "ios.settings.audio", state: "idle"),
    QAVisualReviewRow(id: "ios.settings.audio.loading", state: "loading"),
    QAVisualReviewRow(id: "ios.settings.audio.empty", state: "empty"),
    QAVisualReviewRow(id: "ios.settings.audio.dirty", state: "dirty"),
    QAVisualReviewRow(id: "ios.settings.audio.applying", state: "applying"),
    QAVisualReviewRow(id: "ios.settings.audio.success", state: "success"),
    QAVisualReviewRow(id: "ios.settings.audio.error", state: "error"),
    QAVisualReviewRow(id: "ios.settings.model", state: "idle"),
    QAVisualReviewRow(id: "ios.settings.model.loading", state: "loading"),
    QAVisualReviewRow(id: "ios.settings.model.empty", state: "empty"),
    QAVisualReviewRow(id: "ios.settings.model.dirty", state: "dirty"),
    QAVisualReviewRow(id: "ios.settings.model.applying", state: "applying"),
    QAVisualReviewRow(id: "ios.settings.model.success", state: "success"),
    QAVisualReviewRow(id: "ios.settings.model.error", state: "error"),
    QAVisualReviewRow(id: "ios.settings.tools", state: "idle"),
    QAVisualReviewRow(id: "ios.settings.tools.loading", state: "loading"),
    QAVisualReviewRow(id: "ios.settings.tools.empty", state: "empty"),
    QAVisualReviewRow(id: "ios.settings.tools.dirty", state: "dirty"),
    QAVisualReviewRow(id: "ios.settings.tools.applying", state: "applying"),
    QAVisualReviewRow(id: "ios.settings.tools.success", state: "success"),
    QAVisualReviewRow(id: "ios.settings.tools.error", state: "error"),
    QAVisualReviewRow(id: "ios.settings.system-prompt", state: "idle"),
    QAVisualReviewRow(id: "ios.settings.system-prompt.loading", state: "loading"),
    QAVisualReviewRow(id: "ios.settings.system-prompt.empty", state: "empty"),
    QAVisualReviewRow(id: "ios.settings.system-prompt.dirty", state: "dirty"),
    QAVisualReviewRow(id: "ios.settings.system-prompt.applying", state: "applying"),
    QAVisualReviewRow(id: "ios.settings.system-prompt.success", state: "success"),
    QAVisualReviewRow(id: "ios.settings.system-prompt.error", state: "error"),
    QAVisualReviewRow(id: "ios.settings.advanced", state: "idle"),
    QAVisualReviewRow(id: "ios.settings.advanced.loading", state: "loading"),
    QAVisualReviewRow(id: "ios.settings.advanced.empty", state: "empty"),
    QAVisualReviewRow(id: "ios.settings.advanced.dirty", state: "dirty"),
    QAVisualReviewRow(id: "ios.settings.advanced.applying", state: "applying"),
    QAVisualReviewRow(id: "ios.settings.advanced.success", state: "success"),
    QAVisualReviewRow(id: "ios.settings.advanced.error", state: "error"),
    QAVisualReviewRow(id: "ios.settings.account", state: "idle"),
    QAVisualReviewRow(id: "ios.settings.account.loading", state: "loading"),
    QAVisualReviewRow(id: "ios.settings.account.empty", state: "empty"),
    QAVisualReviewRow(id: "ios.settings.account.dirty", state: "dirty"),
    QAVisualReviewRow(id: "ios.settings.account.applying", state: "applying"),
    QAVisualReviewRow(id: "ios.settings.account.success", state: "success"),
    QAVisualReviewRow(id: "ios.settings.account.error", state: "error"),
    QAVisualReviewRow(id: "ios.settings.members", state: "idle"),
    QAVisualReviewRow(id: "ios.settings.members.loading", state: "loading"),
    QAVisualReviewRow(id: "ios.settings.members.empty", state: "empty"),
    QAVisualReviewRow(id: "ios.settings.members.dirty", state: "dirty"),
    QAVisualReviewRow(id: "ios.settings.members.applying", state: "applying"),
    QAVisualReviewRow(id: "ios.settings.members.success", state: "success"),
    QAVisualReviewRow(id: "ios.settings.members.error", state: "error"),
    QAVisualReviewRow(id: "ios.settings.secrets", state: "idle"),
    QAVisualReviewRow(id: "ios.settings.secrets.loading", state: "loading"),
    QAVisualReviewRow(id: "ios.settings.secrets.empty", state: "empty"),
    QAVisualReviewRow(id: "ios.settings.secrets.dirty", state: "dirty"),
    QAVisualReviewRow(id: "ios.settings.secrets.applying", state: "applying"),
    QAVisualReviewRow(id: "ios.settings.secrets.success", state: "success"),
    QAVisualReviewRow(id: "ios.settings.secrets.error", state: "error"),
    QAVisualReviewRow(id: "ios.settings.diagnostics", state: "idle"),
    QAVisualReviewRow(id: "ios.settings.diagnostics.loading", state: "loading"),
    QAVisualReviewRow(id: "ios.settings.diagnostics.empty", state: "empty"),
    QAVisualReviewRow(id: "ios.settings.diagnostics.dirty", state: "dirty"),
    QAVisualReviewRow(id: "ios.settings.diagnostics.applying", state: "applying"),
    QAVisualReviewRow(id: "ios.settings.diagnostics.success", state: "success"),
    QAVisualReviewRow(id: "ios.settings.diagnostics.error", state: "error"),
    QAVisualReviewRow(id: "ios.settings.change-pin", state: "idle"),
    QAVisualReviewRow(id: "ios.settings.change-pin.invalid", state: "invalid"),
    QAVisualReviewRow(id: "ios.settings.change-pin.saving", state: "saving"),
    QAVisualReviewRow(id: "ios.settings.change-pin.error", state: "error"),
    QAVisualReviewRow(id: "ios.settings.change-pin.success", state: "success"),
    QAVisualReviewRow(id: "ios.settings.member-add", state: "idle"),
    QAVisualReviewRow(id: "ios.settings.member-add.invalid", state: "invalid"),
    QAVisualReviewRow(id: "ios.settings.member-add.saving", state: "saving"),
    QAVisualReviewRow(id: "ios.settings.member-add.error", state: "error"),
    QAVisualReviewRow(id: "ios.settings.member-add.success", state: "success"),
    QAVisualReviewRow(id: "ios.settings.personality-create", state: "idle"),
    QAVisualReviewRow(id: "ios.settings.personality-create.loading", state: "loading"),
    QAVisualReviewRow(id: "ios.settings.personality-create.empty", state: "empty"),
    QAVisualReviewRow(id: "ios.settings.personality-create.dirty", state: "dirty"),
    QAVisualReviewRow(id: "ios.settings.personality-create.applying", state: "applying"),
    QAVisualReviewRow(id: "ios.settings.personality-create.success", state: "success"),
    QAVisualReviewRow(id: "ios.settings.personality-create.error", state: "error"),
    QAVisualReviewRow(id: "ios.settings.voice-record", state: "idle"),
    QAVisualReviewRow(id: "ios.settings.voice-record.loading", state: "loading"),
    QAVisualReviewRow(id: "ios.settings.voice-record.empty", state: "empty"),
    QAVisualReviewRow(id: "ios.settings.voice-record.dirty", state: "dirty"),
    QAVisualReviewRow(id: "ios.settings.voice-record.applying", state: "applying"),
    QAVisualReviewRow(id: "ios.settings.voice-record.success", state: "success"),
    QAVisualReviewRow(id: "ios.settings.voice-record.error", state: "error"),
    QAVisualReviewRow(id: "ios.calendar.route", state: "Calendar route and scaffold"),
    QAVisualReviewRow(id: "ios.calendar.loading", state: "initial loading and background refresh"),
    QAVisualReviewRow(id: "ios.calendar.empty", state: "empty or unavailable calendar"),
    QAVisualReviewRow(id: "ios.calendar.error", state: "load error"),
    QAVisualReviewRow(id: "ios.calendar.error.mutation-error", state: "mutation error"),
    QAVisualReviewRow(id: "ios.calendar.day", state: "Day view"),
    QAVisualReviewRow(id: "ios.calendar.week", state: "Week view"),
    QAVisualReviewRow(id: "ios.calendar.month", state: "Month view"),
    QAVisualReviewRow(id: "ios.calendar.year", state: "Year view"),
    QAVisualReviewRow(id: "ios.calendar.filters", state: "selected"),
    QAVisualReviewRow(id: "ios.calendar.filters.no-match", state: "no match"),
    QAVisualReviewRow(id: "ios.calendar.preview", state: "native event preview sheet"),
    QAVisualReviewRow(id: "ios.calendar.editor", state: "create clean"),
    QAVisualReviewRow(id: "ios.calendar.editor.edit-clean", state: "edit clean"),
    QAVisualReviewRow(id: "ios.calendar.editor.dirty", state: "dirty"),
    QAVisualReviewRow(id: "ios.calendar.editor.saving", state: "saving"),
    QAVisualReviewRow(id: "ios.calendar.editor.error", state: "error"),
    QAVisualReviewRow(id: "ios.calendar.editor.success", state: "success"),
    QAVisualReviewRow(id: "ios.calendar.delete", state: "confirmation"),
    QAVisualReviewRow(id: "ios.calendar.delete.applying", state: "applying"),
    QAVisualReviewRow(id: "ios.calendar.delete.error", state: "error"),
    QAVisualReviewRow(id: "ios.calendar.delete.success", state: "success"),
    QAVisualReviewRow(id: "ios.calendar.recurrence-scope", state: "native recurrence scope chooser"),
]
